apiVersion: admin.gloo.solo.io/v2
kind: IstioLifecycleManager
metadata:
  name: gloo-gateway
  namespace: gloo-mesh
spec:
  clusters:
    - name: mgmt-cluster
  installations:
    - name: control-plane
      istioOperatorSpec:
        profile: minimal
        tag: 1.13.4-arm
        hub: us-docker.pkg.dev/gloo-mesh/istio-a9797008feb0
        components:
          ingressGateways:
          - name: istio-ingressgateway
            enabled: false
    - name: ingress-gateway
      istioOperatorSpec:
        profile: empty
        tag: 1.13.4-arm
        hub: us-docker.pkg.dev/gloo-mesh/istio-a9797008feb0
        components:
          ingressGateways:
          - name: gloo-gateway
            namespace: gloo-gateway
            enabled: true
            k8s:
              service:
                type: LoadBalancer
                ports:
                  # health check port (required to be first for aws elbs)
                  - name: status-port
                    port: 15021
                    targetPort: 15021
                  # main http ingress port
                  - port: 80
                    targetPort: 8080
                    name: http2
                  # main https ingress port
                  - port: 443
                    targetPort: 8443
                    name: https