apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-foundation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/asayah/gloo-mesh-ops
    targetRevision: HEAD
    path: manifests/admin/0-foundation
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false